json.first_name inside_student.first_name
json.last_name inside_student.last_name
json.email inside_student.email
json.phone_number inside_student.phone_number
json.short_bio inside_student.short_bio
json.linkedin inside_student.linkedin
json.twitter inside_student.twitter
json.website inside_student.website
json.resume inside_student.resume
json.github inside_student.github
json.photo inside_student.photo
